### ISSUE TITLE
Code coverage drops after updating xunit.runner.visualstudio to v2.5.0

### ISSUE THREAD

**Issue by Bond-009** [xunit/visualstudio.xunit#381]
After updating xunit.runner.visualstudio our code coverage dropped significantly. Looking at the classes where coverage dropped it shows 2 files one locally and one on GitHub. Based on this I'm assuming that xunit.runner.visualstudio v2.5.0 somehow includes links from Microsoft.SourceLink.GitHub as source files.

Example: https://cov.b0n.dev/jellyfin/Emby.Naming_AlbumParser.html

**Comment by bradwilson** [comment]
The only changed we've made regarding code coverage was to ensure that the test adapter wasn't included in the coverage result: https://github.com/xunit/visualstudio.xunit/commit/86c0e57f3d8458b8b0f5e436f732dd9546d563dd

That should not impact your code at all. How are you collecting coverage? Can you provide a repro project?

**Comment by ValMati** [comment]
We have detected the same problem in two different applications. In both cases there are projects that have no tests and some of them are being excluded from the coverage calculation.

We run the tests and generate the code coverage reports in Azure DevOps. These are the tasks:

```
        # Test Solution
        - task: DotNetCoreCLI@2
          displayName: "Unit Tests"
          inputs:
            command: 'test'
            projects: "$(solution)"
            publishTestResults: false
            arguments: '--filter DisplayName!~MyApplication.IntegrationTests --configuration Release --settings $(Build.SourcesDirectory)\CodeCoverage.runsettings --logger trx --results-directory $(Build.SourcesDirectory)\TestData\'
            nobuild: true
          continueOnError: false

        # Merge code coverage files
        - task: reportgenerator@5
          displayName: "Generate Reports"
          inputs:
            reports: '$(Build.SourcesDirectory)\TestData\**\*.Cobertura.xml'
            targetdir: '$(Build.SourcesDirectory)\coverlet\reports'
            reporttypes: 'HtmlInline_AzurePipelines_Dark;Cobertura'
            verbosity: 'Verbose'

        # Publish code coverage files
        - task: PublishCodeCoverageResults@1
          displayName: "Publish Code Coverage Report"
          inputs:
            codeCoverageTool: 'Cobertura'
            summaryFileLocation: '$(Build.SourcesDirectory)\coverlet\reports\Cobertura.xml'
            failIfCoverageEmpty: true  
```
